### ISSUE TITLE
question about run_all_snv_catalog.sh

### ISSUE THREAD

**Issue by zckoo007** [zjshi/snv_analysis_almeida2019#1]
Hi

Thanks for sharing the code,

I want to ask if this auto.tsv file is missing?

where is the auto.tsv ?

![image](https://user-images.githubusercontent.com/25576334/99935414-9d77ff80-2d9b-11eb-9e96-2cd9139ebe71.png)

**Comment by zjshi** [comment]
Hi, thanks for the question. The noAuto.tsv files are some intermediate files generated from a previous line (#32). Hope this helps. The script "run_all_snv_catalog.sh" should supposedly generate everything from scratch. Let me know please if you encounter any issues running it.
